name: using multiple env variables
on: [push, workflow_dispatch]
env:                          #--------------- We can say these are the global variables which can be used at any stage, job in the workflow ----#
  name: utkarsh
  surname: patil
jobs:
  printingnames:
    runs-on: utkarsh
    steps:
      - run: ehco 'hello my name is ${{ name }}'
      - run: echo 'my surname is ${{$surname}}'
      - run: echo 'today is ${{ date }}'
        env:              #------- Here we are describing a new variable with date in the first job steps -----#
          date: 13-Octomber
  tomorrowdateandfriendname:
      runs-on: utkarsh
      env:         #-------Here we are describing new variables for stage 2 i.e. printing name and tomorrow's date -------#
            friend_name: rohan
            friend_surname: patkar
            tomorrow_date: 14-Octomber
      steps:
        - run: echo 'my friend name is ${{ friend_name }}'
        - run: echo 'my friend surname is ${{ friend_surname }}'
        - run: echo 'tomorrows_date will be ${{ tomorrow_date }}'
