name: Job_1
on:
  workflow_dispatch
env:
  name: utkarsh
  surname: patil
jobs:
  build:
    runs-on:
      - self-hosted
    steps:
    - name: printing names
    - run: echo 'My name is ${{ env.name }}'
    - run: echo 'My surname is ${{ env.surname }}'
