name: Job_1
on: push
env:
  name: utkarsh
  surname: patil
jobs:
  build:
    runs-on: utkarsh
    steps:
    - run: echo 'My name is ${{ env.name }}'
    - run: echo 'My surname is ${{ env.surname }}'
